on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js v10
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: yarn
      - name: npm install, build, and test
        run: |
          yarn install --flozen-lockfile
      - name: workaround for detached HEAD
        run: |
          git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull
      - name: run reg-suit setup
        run: |
          yarn build-storybook
          yarn storycap
      - name: run reg-suit
        run: |
          yarn reg-suit run